version: '3'

services:
  # Sonarr is for series download automation
  sonarr:
    image: mdhiggins/sonarr-sma
    container_name: adamino-sonarr
    volumes:
      - ./sonarr-data:/config
      - ./config:/usr/local/sma/config
      # Set to folder with shows
      - /volume1/Series/TV show:/tv
      # Set to download folder
      - /volume1/Download/complete:/downloads
    ports:
      - 8989:8989
    environment:
      # Set to user with access to folders
      - PUID=1026
      # Set to user group with access to folders
      - PGID=65538
      # Set timezone for logs
      - TZ=Europe/Copenhagen
    restart: always

  # Radarr is for movie download automation
  radarr:
    image: mdhiggins/radarr-sma
    container_name: adamino-radarr
    volumes:
      - ./radarr-data:/config
      - ./config:/usr/local/sma/config
      # Set to folder with movies
      - /volume2/Movies:/movies
      # Set to download folder
      - /volume1/Download/complete:/downloads
    ports:
      - 7878:7878
    environment:
      # Set to user with access to folders
      - PUID=1026
      # Set to user group with access to folders
      - PGID=65538
      # Set timezone for logs
      - TZ=Europe/Copenhagen
    restart: always

  # Bazaar is for subtitle download automation
  bazarr:
    image: linuxserver/bazarr
    container_name: adamino-bazarr
    volumes:
      - ./bazarr-data:/config
      # Set to folder with movies
      - /volume2/Movies:/movies
      # Set to folder with shows
      - /volume1/Series/TV show:/tv
    ports:
      - 6767:6767
    environment:
      # Set to user with access to folders
      - PUID=1026
      # Set to user group with access to folders
      - PGID=65538
      # Set timezone for logs
      - TZ=Europe/Copenhagen
    restart: always
