version: '3'

services:
  sonarr:
    image: mdhiggins/sonarr-sma
    container_name: adamino-sonarr
    volumes:
      - ./sonarr-data:/config
      - ./config:/usr/local/sma/config
      - /volume1/Series/TV show:/tv
      - /volume1/Download/complete:/downloads
    ports:
      - 1337:8989
    environment:
      - PUID=1026
      - PGID=65538
    restart: always

  radarr:
    image: mdhiggins/radarr-sma
    container_name: adamino-radarr
    volumes:
      - ./radarr-data:/config
      - ./config:/usr/local/sma/config
      - /volume2/Movies:/movies
      - /volume1/Download/complete:/downloads
    ports:
      - 7878:7878
    environment:
      - PUID=1026
      - PGID=65538
    restart: always

  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - ./portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
